package net.torocraft.jakel.loot;

public class Modifer {
  public enum Type { FIRE, WITHER, LIGHTNING, COLD, HOLY, XP, MOVEMENT_SPEED, JUMP, HP, REGEN, DEFENSE, INCREASED_XP_GAIN,
    CRITICAL_HIT_CHANCE, CRITICAL_HIT_DAMAGE, SOCKET, MANA_COST, FIRE_RESIST, WITHER_RESIST, LIGHTNING_RESIST, COLD_RESIST,
    HOLY_RESIST, CONTROL_IMPAIRMENT, ATTACK_SPEED, AREA_DAMAGE, LIFE_PER_HIT, LIFE_PER_KILL, THORNS
  }
  public float percent;
  public int amount;

}
